---

- name: Install LibreOffice
  apt:
    name:
      - libreoffice 
    state: present
    update_cache: yes
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

